// auth
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// post
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const LOAD_POSTS_REQUEST = 'LOAD_POSTS_REQUEST';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_ERROR = 'LOAD_POSTS_ERROR';

export const INTERACT_POST_REQUEST = 'INTERACT_POST_REQUEST';
export const INTERACT_POST_SUCCESS = 'INTERACT_POST_SUCCESS';
export const INTERACT_POST_ERROR = 'INTERACT_POST_ERROR';
/*
export const UNLIKE_POST_REQUEST = 'UNLIKE_POST_REQUEST';
export const UNLIKE_POST_SUCCESS = 'UNLIKE_POST_SUCCESS';
export const UNLIKE_POST_ERROR = 'UNLIKE_POST_ERROR';

export const DISLIKE_POST_REQUEST = 'DISLIKE_POST_REQUEST';
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS';
export const DISLIKE_POST_ERROR = 'DISLIKE_POST_ERROR';

export const UNDISLIKE_POST_REQUEST = 'UNDISLIKE_POST_REQUEST';
export const UNDISLIKE_POST_SUCCESS = 'UNDISLIKE_POST_SUCCESS';
export const UNDISLIKE_POST_ERROR = 'UNDISLIKE_POST_ERROR';*/

// comment
export const SET_COMMENTS = 'SET_COMMENTS';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';

export const LOAD_COMMENTS_REQUEST = 'LOAD_COMMENTS_REQUEST';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_COMMENTS_ERROR = 'LOAD_COMMENTS_ERROR';

export const INTERACT_COMMENT_REQUEST = 'INTERACT_COMMENT_REQUEST';
export const INTERACT_COMMENT_SUCCESS = 'INTERACT_COMMENT_SUCCESS';
export const INTERACT_COMMENT_ERROR = 'INTERACT_COMMENT_ERROR';

// user
export const SET_USERS = 'SET_USERS';
export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_ERROR = 'SEARCH_USER_ERROR';