export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATING_POST = 'CREATING_POST';
export const POST_CREATED_SUCCESS = 'POST_CREATED_SUCCESS';
export const POST_CREATED_ERROR = 'POST_CREATED_ERROR';
export const FETCHING_POSTS = 'FETCHING_POSTS';
export const POSTS_FETCHED = 'POSTS_FETCHED';

export const CREATING_COMMENT = 'CREATING_COMMENT';
export const COMMENT_CREATED_SUCCESS = 'COMMENT_CREATED_SUCCESS';
export const COMMENT_CREATED_ERROR = 'COMMENT_CREATED_ERROR';
export const FETCHING_COMMENTS = 'FETCHING_COMMENTS';
export const COMMENTS_FETCHED = 'COMMENTS_FETCHED';


export const GET_POSTS = 'GET_POSTS';
export const LOGGING_OUT = 'LOGGING_OUT';
export const LOGGED_OUT = 'LOGGED_OUT';